# Generated by Django 4.2.4 on 2023-09-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_alter_actividad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='area',
            field=models.CharField(default='Area', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='tema',
            field=models.CharField(default='Tema', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuario',
            field=models.CharField(default='Usuario', max_length=100),
            preserve_default=False,
        ),
    ]
