# Generated by Django 4.2.4 on 2023-09-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_actividad_area_actividad_tema_actividad_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
    ]
